openapi: 3.0.3
info:
  title: Account Group API
  version: 1.0.0

paths:
  /api/account-group/create:
    post:
      tags: [account-group]
      summary: Create account group
      operationId: createAccountGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountGroupRequest'
      responses:
        '200':
          description: Account group created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountGroupResponseWrapper'

  /api/account-group/list-all:
    get:
      tags: [account-group]
      summary: List account groups
      operationId: listAccountGroups
      responses:
        '200':
          description: List of account groups
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountGroupListResponseWrapper'

components:
  schemas:
    AccountGroupRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          example: Customers
        parentId:
          type: integer
          format: int64
          example: 1

    AccountGroupResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Customers

    AccountGroupResponseWrapper:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          $ref: '#/components/schemas/AccountGroupResponse'

    AccountGroupListResponseWrapper:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
        data:
          type: array
          items:
            $ref: '#/components/schemas/AccountGroupResponse'
