openapi: 3.0.3
info:
  title: Broker API
  version: 1.0.0

paths:
  /api/broker/create:
    post:
      tags: [broker]
      summary: Create broker
      operationId: createBroker
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BrokerRequest'
      responses:
        '200':
          description: Broker created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrokerResponse'

  /api/broker/list-all:
    get:
      tags: [broker]
      summary: List brokers
      operationId: listBrokers
      responses:
        '200':
          description: List of brokers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BrokerResponse'

components:
  schemas:
    BrokerRequest:
      type: object
      required: [name]
      properties:
        name:
          type: string
          example: Rajesh Kumar
        phone:
          type: string
          example: '9876543210'

    BrokerResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: Rajesh Kumar
        phone:
          type: string
          example: '9876543210'
        createdAt:
          type: string
          format: date-time
