openapi: 3.0.3
info:
  title: State API
  version: 1.0.0

paths:
  /api/state/list-all:
    get:
      tags: [state]
      summary: List all states
      operationId: listAllStates
      responses:
        '200':
          description: List of states
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StateResponse'

components:
  schemas:
    StateResponse:
      type: object
      properties:
        code:
          type: string
          example: UP
        name:
          type: string
          example: Uttar Pradesh
